### ISSUE TITLE
SDK is for PB741 (Inkpad Color)?

### ISSUE THREAD

**Issue by clort81** [pocketbook/SDK_6.3.0#5]
I have Inkpad Color PB741 and would like matching SDK.
Software version:L U741.6.5.1684.

Does this work for it or can you point me (and other users who find this) to correct SDK for 6.5 FW?

**Comment by rjd22** [comment]
I actually mailed PocketBook for this and they updated the SDK for us. You can find it here:

https://github.com/pocketbook/SDK_6.3.0/tree/6.5/SDK-B288

**Comment by clort81** [comment]
Wow, Thanks!
